import nltk so that we don't get told "NameError: global name 'nltk' is not defined"
BRIAN-TINGLEs-MacBook-Air:scrub_sample tingle$ python example1.py 
Traceback (most recent call last):
  File "example1.py", line 10, in <module>
    chunked_sentences = nltk.batch_ne_chunk(tagged_sentences, binary=True)
  File "/usr/local/Cellar/python/2.7.2/lib/python2.7/site-packages/nltk-2.0.1rc2_git-py2.7.egg/nltk/chunk/__init__.py", line 185, in batch_ne_chunk
    chunker = nltk.data.load(chunker_pickle)
NameError: global name 'nltk' is not defined